### ISSUE TITLE
How about know the coordinator & worker address on yarn?

### ISSUE THREAD

**Issue by FanTn** [prestodb/presto-yarn#33]
Hi:
   The slider-presto application is running on yarn, but I don not know the coordinator & worker address,and how to post the query statement

The app master info : 

```
Application: presto1

Status  all containers allocated
Total number of containers  1
Create time:    10 Dec 2015 06:09:14 GMT
Running since:  10 Dec 2015 06:09:14 GMT
Time last flexed:   N/A
Application storage path:   hdfs://ras/user/hadoop/.slider/cluster/presto1/database
Application configuration path: hdfs://ras/user/hadoop/.slider/cluster/presto1/snapshot
Component Instances
Component   Desired Actual  Outstanding Requests    Failed  Failed to start
COORDINATOR 1   0   0   0   0
WORKER  3   0   0   0   0
slider-appmaster    1   1   0   0   0
Slider Agent information
http:// http://192.168.172.85:1025
classpath:org.apache.slider.client.rest http://192.168.172.85:1025
classpath:org.apache.slider.management http://192.168.172.85:1025/ws/v1/slider/mgmt
classpath:org.apache.slider.publisher http://192.168.172.85:1025/ws/v1/slider/publisher
classpath:org.apache.slider.registry http://192.168.172.85:1025/ws/v1/slider/registry
classpath:org.apache.slider.publisher.configurations http://192.168.172.85:1025/ws/v1/slider/publisher/slider
classpath:org.apache.slider.publisher.exports http://192.168.172.85:1025/ws/v1/slider/publisher/exports
slider-appmaster Host(s)/Container(s): [192.168.172.85/container_1449481829213_0011_01_000001]
```

Cluster Specification

```
{
  "version" : "1.0",
  "name" : "presto1",
  "type" : "agent",
  "state" : 3,
  "createTime" : 1449727754065,
  "updateTime" : 1449727755737,
  "originConfigurationPath" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/snapshot",
  "generatedConfigurationPath" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/generated",
  "dataPath" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/database",
  "options" : {
    "internal.container.failure.shortlife" : "60000",
    "internal.container.failure.threshold" : "5",
    "internal.generated.conf.path" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/generated",
    "env.MALLOC_ARENA_MAX" : "4",
    "internal.am.tmp.dir" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/tmp/appmaster",
    "internal.snapshot.conf.path" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/snapshot",
    "zookeeper.hosts" : "192.168.172.80,192.168.172.81,192.168.172.82",
    "site.global.coordinator_host" : "${COORDINATOR_HOST}",
    "internal.data.dir.path" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/database",
    "internal.addons.dir.path" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/tmp/addons",
    "site.global.user_group" : "hadoop",
    "site.global.data_dir" : "/data10/presto/data",
    "site.global.presto_query_max_memory" : "5GB",
    "site.global.presto_query_max_memory_per_node" : "600MB",
    "internal.application.home" : null,
    "internal.provider.name" : "agent",
    "yarn.vcores" : "1",
    "site.global.security_enabled" : "false",
    "site.global.catalog" : "{'hive': ['connector.name=hive-cdh5', 'hive.metastore.uri=thrift://192.168.177.82:9083']}",
    "java_home" : "/software/servers/jdk1.8.0_40",
    "zookeeper.quorum" : "192.168.172.80:2182,192.168.172.81:2182,192.168.172.82:2182",
    "slider.cluster.directory.permissions" : "0770",
    "internal.tmp.dir" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/tmp",
    "slider.data.directory.permissions" : "0770",
    "application.def" : ".slider/package/PRESTO/presto-yarn-package-1.0.0-SNAPSHOT.zip",
    "site.global.app_name" : "presto-server-0.123",
    "zookeeper.path" : "/services/slider/users/hadoop/presto1",
    "site.global.app_user" : "hadoop",
    "site.global.app_pkg_plugin" : "${AGENT_WORK_ROOT}/app/definition/package/plugins/",
    "site.global.jvm_args" : "['-server', '-Xmx10240M', '-XX:+UseG1GC', '-XX:G1HeapRegionSize=32M', '-XX:+UseGCOverheadLimit', '-XX:+ExplicitGCInvokesConcurrent', '-XX:+HeapDumpOnOutOfMemoryError', '-XX:OnOutOfMemoryError=kill -9 %p']",
    "internal.application.image.path" : null,
    "internal.appdef.dir.path" : "hdfs://ras/user/hadoop/.slider/cluster/presto1/tmp/appdef",
    "site.fs.defaultFS" : "hdfs://ras",
    "site.global.presto_server_port" : "9100",
    "site.global.singlenode" : "true",
    "site.fs.default.name" : "hdfs://ras",
    "application.name" : "presto1"
  },
  "info" : {
    "yarn.vcores" : "28",
    "info.am.app.id" : "application_1449481829213_0011",
    "yarn.memory" : "25600",
    "info.am.web.url" : "http://192.168.172.85:1025/",
    "info.am.rpc.port" : "1024",
    "info.am.hostname" : "192.168.172.85",
    "info.am.web.port" : "1025",
    "info.am.container.id" : "container_1449481829213_0011_01_000001",
    "info.am.attempt.id" : "appattempt_1449481829213_0011_000001",
    "status.application.build.info" : "Slider Core-0.81.1-incubating Built against commit# a9b1d659c6 on Java 1.7.0_55 by jmaron",
    "status.hadoop.build.info" : "2.6.0",
    "status.hadoop.deployed.info" : "(detached from 15ecc87) @fc0a1a23fc1868e4d5ee7fa2b28a58a",
    "live.time" : "10 Dec 2015 06:09:14 GMT",
    "live.time.millis" : "1449727754065",
    "create.time" : "10 Dec 2015 06:09:14 GMT",
    "create.time.millis" : "1449727754065",
    "containers.at.am-restart" : "0",
    "status.time" : "10 Dec 2015 06:50:05 GMT",
    "status.time.millis" : "1449730205250",
    "info.am.agent.status.url" : "https://192.168.172.85:58603/",
    "info.am.agent.ops.url" : "https://192.168.172.85:12119/",
    "info.am.agent.ops.port" : "12119",
    "info.am.agent.status.port" : "58603"
  },
  "statistics" : {
    "COORDINATOR" : {
      "containers.failed.preempted" : 0,
      "containers.completed" : 0,
      "containers.failed" : 0,
      "containers.requested" : 0,
      "containers.desired" : 1,
      "containers.start.failed" : 0,
      "containers.start.started" : 0,
      "containers.failed.node" : 0,
      "containers.active.requests" : 0,
      "containers.live" : 0,
      "containers.failed.recently" : 0
    },
    "slider-appmaster" : {
      "containers.completed" : 0,
      "containers.failed" : 0,
      "containers.unknown.completed" : 0,
      "containers.surplus" : 0,
      "containers.start.failed" : 0,
      "containers.start.started" : 0,
      "containers.live" : 1
    },
    "WORKER" : {
      "containers.failed.preempted" : 0,
      "containers.completed" : 0,
      "containers.failed" : 0,
      "containers.requested" : 0,
      "containers.desired" : 3,
      "containers.start.failed" : 0,
      "containers.start.started" : 0,
      "containers.failed.node" : 0,
      "containers.active.requests" : 0,
      "containers.live" : 0,
      "containers.failed.recently" : 0
    }
  },
  "instances" : {
    "slider-appmaster" : [ "container_1449481829213_0011_01_000001" ]
  },
  "roles" : {
    "COORDINATOR" : {
      "yarn.vcores" : "1",
      "yarn.label.expression" : "coordinator",
      "yarn.role.priority" : "1",
      "yarn.memory" : "2048",
      "role.releasing.instances" : "0",
      "role.failed.node.instances" : "0",
      "role.requested.instances" : "0",
      "role.actual.instances" : "0",
      "role.failed.recently.instances" : "0",
      "role.failed.starting.instances" : "0",
      "yarn.component.instances" : "1",
      "role.failed.preempted.instances" : "0",
      "role.failed.instances" : "0",
      "yarn.component.placement.policy" : "1"
    },
    "slider-appmaster" : {
      "yarn.vcores" : "1",
      "yarn.component.instances" : "1",
      "yarn.memory" : "1024",
      "role.releasing.instances" : "0",
      "role.failed.preempted.instances" : "0",
      "role.failed.node.instances" : "0",
      "role.requested.instances" : "0",
      "role.failed.instances" : "0",
      "role.actual.instances" : "1",
      "role.failed.recently.instances" : "0",
      "role.failed.starting.instances" : "0"
    },
    "WORKER" : {
      "yarn.vcores" : "1",
      "yarn.label.expression" : "worker",
      "yarn.role.priority" : "2",
      "yarn.memory" : "2048",
      "role.releasing.instances" : "0",
      "role.failed.node.instances" : "0",
      "role.requested.instances" : "0",
      "role.actual.instances" : "0",
      "role.failed.recently.instances" : "0",
      "role.failed.starting.instances" : "0",
      "yarn.component.instances" : "3",
      "role.failed.preempted.instances" : "0",
      "role.failed.instances" : "0",
      "yarn.component.placement.policy" : "1"
    }
  },
  "clientProperties" : { },
  "status" : {
    "live" : {
      "slider-appmaster" : {
        "container_1449481829213_0011_01_000001" : {
          "name" : "container_1449481829213_0011_01_000001",
          "role" : "slider-appmaster",
          "roleId" : 0,
          "createTime" : 1449727754093,
          "startTime" : 1449727754093,
          "released" : false,
          "host" : "192.168.172.85",
          "hostUrl" : "http://192.168.172.85:1025",
          "state" : 3,
          "exitCode" : 0
        }
      }
    }
  },
  "liveness" : {
    "allRequestsSatisfied" : true,
    "requestsOutstanding" : 0
  }
}
```

**Comment by anusudarsan** [comment]
@FanTn : From the status output, you just have slider-appmaster running and not any COORDINATOR and WORKER components up (See  "status" : {
    "live" : { section in the output you pasted). That section of the status output should also give the hostnames of coordinator and workers (like you have for slider-appmaster). You could look at your YARN container logs as to why those components failed? See the "Debugging and Logging" section in the README for details of log location and how to debug what went wrong. 

Also from your configuration, it looks like you have labels configured for the components, "yarn.label.expression" : "coordinator", This means your coordinator will be ALWAYS running on a node which you "labelled" as "coordinator". If you have not labelled your YARN nodes yet, please do it following the steps here http://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.3.0/bk_yarn_resource_mgt/content/configuring_node_labels.html. You can also find the yarn-site.xml and capacity-scheduler.xml files we use for our testing of YARN labels here - https://github.com/prestodb/presto-yarn/tree/master/presto-yarn-test/src/test/resources/conf/yarn

**Comment by FanTn** [comment]
@anusudarsan  Thanks a lot ,I will retry.

**Comment by FanTn** [comment]
@anusudarsan  You are right, I look at the container logs, I found the error log as follow : 

```
2015-12-11 11:01:10,349 [AmExecutor-006] INFO  appmaster.SliderAppMaster - Registered service under /users/hadoop/services/org-apache-slider/presto1; absolute path /registry/users/hadoop/services/org-apache-slider/presto1
2015-12-11 11:01:10,354 [AmExecutor-006] INFO  state.AppState - Reviewing RoleStatus{name='COORDINATOR', key=1, desired=1, actual=0, requested=0, releasing=0, failed=0, failed recently=0, node failed=0, pre-empted=0, started=0, startFailed=0, completed=0, failureMessage=''} : expected 1
2015-12-11 11:01:10,354 [AmExecutor-006] INFO  state.AppState - COORDINATOR: Asking for 1 more nodes(s) for a total of 1
2015-12-11 11:01:10,359 [AmExecutor-006] ERROR actions.QueueExecutor - Exception processing org.apache.slider.server.appmaster.actions.ReviewAndFlexApplicationSize@4970f53c name='flexCluster', delay=0, attrs=4, sequenceNumber=6}: org.apache.hadoop.yarn.client.api.InvalidContainerRequestException: relax location flag doesn't match container priority: OutstandingRequest{roleId=1, node=null, hostname='null', hasLocation=true, requestedTimeMillis=1449802870357, mayEscalate=false, escalated=true, escalationTimeoutMillis=1449802900357, issuedRequest=Capability[<memory:2048, vCores:1>]Priority[1073741825]; relaxLocality=true; nodeLabels=coordinator; }
org.apache.hadoop.yarn.client.api.InvalidContainerRequestException: relax location flag doesn't match container priority: OutstandingRequest{roleId=1, node=null, hostname='null', hasLocation=true, requestedTimeMillis=1449802870357, mayEscalate=false, escalated=true, escalationTimeoutMillis=1449802900357, issuedRequest=Capability[<memory:2048, vCores:1>]Priority[1073741825]; relaxLocality=true; nodeLabels=coordinator; }
    at org.apache.slider.server.appmaster.state.OutstandingRequest.validate(OutstandingRequest.java:406)
    at org.apache.slider.server.appmaster.state.OutstandingRequest.buildContainerRequest(OutstandingRequest.java:232)
    at org.apache.slider.server.appmaster.state.RoleHistory.requestInstanceOnNode(RoleHistory.java:598)
    at org.apache.slider.server.appmaster.state.RoleHistory.requestNode(RoleHistory.java:613)
    at org.apache.slider.server.appmaster.state.AppState.createContainerRequest(AppState.java:1232)
    at org.apache.slider.server.appmaster.state.AppState.buildContainerResourceAndRequest(AppState.java:1213)
    at org.apache.slider.server.appmaster.state.AppState.reviewOneRole(AppState.java:1938)
    at org.apache.slider.server.appmaster.state.AppState.reviewRequestAndReleaseNodes(AppState.java:1812)
    at org.apache.slider.server.appmaster.SliderAppMaster.executeNodeReview(SliderAppMaster.java:1804)
    at org.apache.slider.server.appmaster.SliderAppMaster.handleReviewAndFlexApplicationSize(SliderAppMaster.java:1790)
    at org.apache.slider.server.appmaster.actions.ReviewAndFlexApplicationSize.execute(ReviewAndFlexApplicationSize.java:41)
    at org.apache.slider.server.appmaster.actions.QueueExecutor.run(QueueExecutor.java:73)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2015-12-11 11:01:10,361 [AmExecutor-006] ERROR appmaster.SliderAppMaster - Exception in AmExecutor-006: org.apache.hadoop.yarn.client.api.InvalidContainerRequestException: relax location flag doesn't match container priority: OutstandingRequest{roleId=1, node=null, hostname='null', hasLocation=true, requestedTimeMillis=1449802870357, mayEscalate=false, escalated=true, escalationTimeoutMillis=1449802900357, issuedRequest=Capability[<memory:2048, vCores:1>]Priority[1073741825]; relaxLocality=true; nodeLabels=coordinator; }
org.apache.hadoop.yarn.client.api.InvalidContainerRequestException: relax location flag doesn't match container priority: OutstandingRequest{roleId=1, node=null, hostname='null', hasLocation=true, requestedTimeMillis=1449802870357, mayEscalate=false, escalated=true, escalationTimeoutMillis=1449802900357, issuedRequest=Capability[<memory:2048, vCores:1>]Priority[1073741825]; relaxLocality=true; nodeLabels=coordinator; }
    at org.apache.slider.server.appmaster.state.OutstandingRequest.validate(OutstandingRequest.java:406)
    at org.apache.slider.server.appmaster.state.OutstandingRequest.buildContainerRequest(OutstandingRequest.java:232)
    at org.apache.slider.server.appmaster.state.RoleHistory.requestInstanceOnNode(RoleHistory.java:598)
    at org.apache.slider.server.appmaster.state.RoleHistory.requestNode(RoleHistory.java:613)
    at org.apache.slider.server.appmaster.state.AppState.createContainerRequest(AppState.java:1232)
    at org.apache.slider.server.appmaster.state.AppState.buildContainerResourceAndRequest(AppState.java:1213)
    at org.apache.slider.server.appmaster.state.AppState.reviewOneRole(AppState.java:1938)
    at org.apache.slider.server.appmaster.state.AppState.reviewRequestAndReleaseNodes(AppState.java:1812)
    at org.apache.slider.server.appmaster.SliderAppMaster.executeNodeReview(SliderAppMaster.java:1804)
    at org.apache.slider.server.appmaster.SliderAppMaster.handleReviewAndFlexApplicationSize(SliderAppMaster.java:1790)
    at org.apache.slider.server.appmaster.actions.ReviewAndFlexApplicationSize.execute(ReviewAndFlexApplicationSize.java:41)
    at org.apache.slider.server.appmaster.actions.QueueExecutor.run(QueueExecutor.java:73)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

But I do not understand what that mean about "relax location flag doesn't match container priority".

**Comment by anusudarsan** [comment]
@FanTn : To me, that error looks like some misconfiguration with YARN labels. Are you sure, you have all the nodes labelled correctly(one node as coordinator and 3 nodes as worker)? Did you check either via http://master:8088/cluster/nodes on your YARN ResourceManager UI or using the yarn command "yarn node -status node_id:45454" (where node_id you can get from "yarn node -list") that the labels are set appropriately? See my above comment about YARN labels.

Also make sure you do not have any misconfiguration in queue settings, like in capacity-scheduler.xml

**Comment by FanTn** [comment]
@anusudarsan  Via RM UI, all the nodes have labelled.

```
coordinator /rack/rack085 RUNNING
coordinator /rack/rack085 RUNNING
coordinator /rack/rack086 RUNNING
coordinator /rack/rack085 RUNNING
coordinator /rack/rack086 RUNNING
worker      /rack/rack086 RUNNING
worker      /rack/rack085 RUNNING
worker      /rack/rack086 RUNNING
worker      /rack/rack086 RUNNING
worker      /rack/rack085 RUNNING
worker      /rack/rack085 RUNNING
```

scheduler queue information : 

```
Queue State:    RUNNING
Used Capacity:  0.0%
Absolute Used Capacity: 0.0%
Absolute Capacity:  100.0%
Absolute Max Capacity:  100.0%
Used Resources: <memory:0, vCores:0>
Num Schedulable Applications:   1
Num Non-Schedulable Applications:   0
Num Containers: 1
Max Applications:   10000
Max Applications Per User:  10000
Max Application Master Resources:   <memory:67584, vCores:1>
Used Application Master Resources:  <memory:2048, vCores:1>
Max Application Master Resources Per User:  <memory:67584, vCores:1>
Configured Capacity:    100.0%
Configured Max Capacity:    100.0%
Configured Minimum User Limit Percent:  100%
Configured User Limit Factor:   1.0
Accessible Node Labels: coordinator,worker
Preemption: disabled
```

**Comment by kokosing** [comment]
It looks like yarn is not able to allocate a container for your coordinator. Make sure you have set correctly the yarn queues (see: http://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.3.0/bk_yarn_resource_mgt/content/ch_node_labels.html).

**Comment by kokosing** [comment]
@FanTn Have you fixed your problem? What was the root cause and (or) solution?

**Comment by FanTn** [comment]
@anusudarsan @kokosing  Thanks a lot. The YARN labels  cause the issue.
