### ISSUE TITLE
start presto-on-yarn package failed

### ISSUE THREAD

**Issue by JasonBian** [prestodb/presto-yarn#59]
```
org.apache.hadoop.yarn.exceptions.InvalidResourceRequestException: Invalid resource request, queue=root.default doesn't have permission to access all labels in resource request. labelExpression of resource request=worker. Queue labels=
	at org.apache.hadoop.yarn.server.resourcemanager.scheduler.SchedulerUtils.validateResourceRequest(SchedulerUtils.java:242)
	at org.apache.hadoop.yarn.server.resourcemanager.RMServerUtils.validateResourceRequests(RMServerUtils.java:96)
	at org.apache.hadoop.yarn.server.resourcemanager.ApplicationMasterService.allocate(ApplicationMasterService.java:501)
	at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationMasterProtocolPBServiceImpl.allocate(ApplicationMasterProtocolPBServiceImpl.java:60)
	at org.apache.hadoop.yarn.proto.ApplicationMasterProtocol$ApplicationMasterProtocolService$2.callBlockingMethod(ApplicationMasterProtocol.java:99)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:619)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2044)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2040)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2038)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateException(RPCUtil.java:53)
	at org.apache.hadoop.yarn.ipc.RPCUtil.unwrapAndThrowException(RPCUtil.java:101)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationMasterProtocolPBClientImpl.allocate(ApplicationMasterProtocolPBClientImpl.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy23.allocate(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.allocate(AMRMClientImpl.java:277)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$HeartbeatThread.run(AMRMClientAsyncImpl.java:237)
```

**Comment by kokosing** [comment]
Can you please add more detail? What version of presto and hadoop do you use? Can you attach the `resource.json` and `appConfig.json` files? What was the use case (scenario)? I mean what you did before spotting this problem.

Generally try to attach as much information as you can. That will help us to diagnose, reproduce and help you to fix this problem. Simple stack trace is not enough.

**Comment by JasonBian** [comment]
@kokosing 
appConfig.json

```
`{
  "schema": "http://example.org/specification/v2.0.0",
  "metadata": {
  },
  "global": {
    "site.global.app_user": "root",
    "site.global.user_group": "hadoop",
    "site.global.data_dir": "/var/lib/presto/data",
    "site.global.config_dir": "/var/lib/presto/etc",
    "site.global.app_name": "presto-server-0.152",
    "site.global.app_pkg_plugin": "${AGENT_WORK_ROOT}/app/definition/package/plugins/",
    "site.global.singlenode": "true",
    "site.global.coordinator_host": "${COORDINATOR_HOST}",
    "site.global.presto_query_max_memory": "50GB",
    "site.global.presto_query_max_memory_per_node": "600MB",
    "site.global.presto_server_port": "8080",

    "site.global.catalog": "{'hive': ['connector.name=hive-hadoop2', 'hive.metastore.uri=thrift://bi-01:9083,thrift://bi-03:9083,thrift://bi-04:9083', 'hive.config.resources=/opt/cloudera/parcels/CD
H/lib/hadoop/etc/hadoop/core-site.xml,/opt/cloudera/parcels/CDH/lib/hadoop/etc/hadoop/hdfs-site.xml', 'hive.allow-drop-table=false']}",
    "site.global.jvm_args": "['-server', '-Xmx1024M', '-XX:+UseG1GC', '-XX:G1HeapRegionSize=32M', '-XX:+UseGCOverheadLimit', '-XX:+ExplicitGCInvokesConcurrent', '-XX:+HeapDumpOnOutOfMemoryError', '-
XX:OnOutOfMemoryError=kill -9 %p']",

    "application.def": ".slider/package/PRESTO/presto-yarn-package-1.4-SNAPSHOT-0.152.zip",
    "java_home": "/usr/java/jdk1.8.0_60/bin/java"
  },
  "components": {
    "slider-appmaster": {
      "jvm.heapsize": "128M"
    }
  }
}`
```

resource.json:

```
{
  "schema": "http://example.org/specification/v2.0.0",
  "metadata": {
  },
  "global": {
    "yarn.vcores": "1"
  },
  "components": {
    "slider-appmaster": {
    },
    "COORDINATOR": {
      "yarn.role.priority": "1",
      "yarn.component.instances": "1",
      "yarn.component.placement.policy": "1",
      "yarn.memory": "1500",
      "yarn.label.expression": "coordinator"
    },
    "WORKER": {
      "yarn.role.priority": "2",
      "yarn.component.instances": "3",
      "yarn.component.placement.policy": "1",
      "yarn.memory": "1500",
      "yarn.label.expression": "worker"
    }
  }
}
```

in my YARN cluster,the nodes without labels

**Comment by kokosing** [comment]
What version of CDH do you use? If you don't have labels set in cluster, can you remove labels configuration from `resources.json`?

**Comment by JasonBian** [comment]
@kokosing CDH-5.4

**Comment by JasonBian** [comment]
@kokosing when I remove labels configuration from resource.json,I got another error:

```
org.apache.slider.core.exceptions.TriggerClusterTeardownException: Unstable Application Instance : - failed with component WORKER failed 'recently' 6 times (3 in startup); threshold is 5 - last failure: Failure container_1476433589512_23574_01_000008 on host bi-04 (0): http://bi-01:19888/jobhistory/logs//bi-04:8041/container_1476433589512_23574_01_000008/ctx/root
    at org.apache.slider.server.appmaster.state.AppState.checkFailureThreshold(AppState.java:1942)
    at org.apache.slider.server.appmaster.state.AppState.reviewOneRole(AppState.java:2048)
    at org.apache.slider.server.appmaster.state.AppState.reviewRequestAndReleaseNodes(AppState.java:1919)
    at org.apache.slider.server.appmaster.SliderAppMaster.executeNodeReview(SliderAppMaster.java:1937)
    at org.apache.slider.server.appmaster.SliderAppMaster.handleReviewAndFlexApplicationSize(SliderAppMaster.java:1923)
    at org.apache.slider.server.appmaster.actions.ReviewAndFlexApplicationSize.execute(ReviewAndFlexApplicationSize.java:41)
    at org.apache.slider.server.appmaster.actions.QueueExecutor.run(QueueExecutor.java:73)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by kokosing** [comment]
Ok, I think you went further. Slider was able to setup application cluster, but it looks like presto was unable to start 6 times in a row.

Try to find presto (`server.log`) logs to see why it fails. You should be able to find these in `/var/lib/presto/data/log`.

**Comment by JasonBian** [comment]
@kokosing there is no server.log under the path /var/lib/presto/data/log.Actually there is no files under the path /var/lib/presto/data/log

**Comment by mattsfuller** [comment]
What is the output of ls -al /var/lib/presto on all your nodes?
You should make sure to have both a data and etc directory under that /var/lib/presto on all nodes.

Not sure if this is your issue here. But I've run into a similar looking problem when I forgot to create those on one of the nodes.

**Comment by JasonBian** [comment]
@mattsfuller thank you for your answer.When I create /var/lib/presto for all yarn nodes,I got the server.log file.

**Comment by mattsfuller** [comment]
Great. Were you able to start it now?

**Comment by JasonBian** [comment]
@mattsfuller yeah,it's ok.Thank you

**Comment by qiuhan** [comment]
@JasonBian I met the same problem. When I removed the labels, server.log said 
"/data7/hadoop/yarn/local-dir/usercache/hadoop/appcache/application_1492734155362_19978/container_e28_1492734155362_19978_01_000010/app/install/presto-yarn/bin/launcher: No such file or directory"
How to fix this problem?
Thanks

**Comment by xjh713** [comment]
@JasonBian  你的这个后面可以使用了吗？我的报这样错"failed with component WORKER failed 'recently' 6 times (6 in startup); threshold is 5 - last failure: Failure "

**Comment by xjh713** [comment]
@mattsfuller now my problem is like this "failed with component WORKER failed 'recently' 6 times (6 in startup); threshold is 5 - last failure: Failure " ,can you help me fix ?

**Comment by kokosing** [comment]
> What is the output of ls -al /var/lib/presto on all your nodes?
You should make sure to have both a data and etc directory under that /var/lib/presto on all nodes.

**Comment by xjh713** [comment]
@kokosing my presto is single node by deployed, "site.global.singlenode": "true" ,etc and data has files,when i submit slider to yarn whitch throws exception like "Unstable Application Instance : - failed with component COORDINATOR failed 'recently' 6 times (5 in startup); threshold is 5 - last failure: Failure container_e19_1533108188813_16214_02_000012"

**Comment by xjh713** [comment]
@kokosing  like my upload picture 
![image](https://user-images.githubusercontent.com/22866545/46776156-f364c700-cd3c-11e8-84f8-d686244e3b30.png)

**Comment by kokosing** [comment]
> What is the output of ls -al /var/lib/presto on all your nodes?

In your case on your single node. Slider tried to run Presto 5 times in a row and each time it failed, you need to find out why Presto does not want to start.

**Comment by xjh713** [comment]
@kokosing well,but how to find out the start? i can need to read slider source code?that is spend time ,i think we should change memory setting ,my picture show virtual memory is  less than

**Comment by anusudarsan** [comment]
@xjh713 Try to find presto (server.log) logs to see why it fails. You should be able to find these in /var/lib/presto/data/log. See https://github.com/prestodb/presto-yarn/issues/59#issuecomment-258789936

**Comment by chengang2** [comment]
@qiuhan 
 I met the same problem. When I removed the labels, server.log said
"/data7/hadoop/yarn/local-dir/usercache/hadoop/appcache/application_1492734155362_19978/container_e28_1492734155362_19978_01_000010/app/install/presto-yarn/bin/launcher: No such file or directory"
How to fix this problem?
Thanks
