### ISSUE TITLE
Presto not starting via slider.

### ISSUE THREAD

**Issue by shahbhavin** [prestodb/presto-yarn#62]
Hello,

I am getting below error in Container log. Where to set this parameter for presto. I belive it is inheriting from yarn.

ERROR actions.QueueExecutor: Exception processing org.apache.slider.server.appmaster.actions.ReviewAndFlexApplicationSize@7370e879 name='onContainersCompleted', delay=0, attrs=4, sequenceNumber=23}: org.apache.hadoop.yarn.client.api.InvalidContainerRequestException: Cannot submit a ContainerRequest asking for location * with locality relaxation false when it has already been requested with locality relaxation true
org.apache.hadoop.yarn.client.api.InvalidContainerRequestException: Cannot submit a ContainerRequest asking for location * with locality relaxation false when it has already been requested with locality relaxation true

Thanks,
B

**Comment by shahbhavin** [comment]
Presto 0.148

**Comment by anusudarsan** [comment]
@shahbhavin  From the error it looks like you are trying to deploy Presto on a cluster with insufficient number of nodemanager nodes. This usually happens when you set the number of components (including coordinator and workers) in resources.json to be more than the actual number of nodemanagers in the cluster. Do you mind sharing your configuration (appconfig and resources) json files? Did you set set labels in YARN?

**Comment by shahbhavin** [comment]
@anusudarsan Thanks for the reply. I have launched this configuration with 1 Coordinator & 1 Worker node. I have 13 Node manager in the Cluster. I have not configured any nodes labels in Yarn. Process can use any host.

Let me know if you require any further details.

**Comment by shahbhavin** [comment]
I am getting error below.

16/12/13 07:13:40 ERROR mortbay.log: Error for /
java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:870)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:834)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:795)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.apache.hadoop.http.HttpServer2$QuotingInputFilter.doFilter(HttpServer2.java:1243)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.apache.hadoop.http.NoCacheFilter.doFilter(NoCacheFilter.java:45)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

This error I was getting earlier for 1.3 version than I downgraded to 1.2.1 than it worked. Now it is again giving error for the same.

**Comment by shahbhavin** [comment]
Detailed Error:

16/12/13 07:48:16 INFO zk.RegistryOperationsService: Bound at /users/yarn/services/org-apache-slider/odbcv1-3-1/components/container-e98-1481218602228-49005-01-000003 : ServiceRecord{description='WORKER'; external endpoints: {}; internal endpoints: {}, attributes: {"yarn:persistence"="container" "yarn:id"="container-e98-1481218602228-49005-01-000003" }}
Dec 13, 2016 7:48:18 AM com.google.inject.servlet.InternalServletModule$BackwardsCompatibleServletContextProvider get
WARNING: You are attempting to use a deprecated API (specifically, attempting to @Inject ServletContext inside an eagerly created singleton. While we allow this for backwards compatibility, be warned that this MAY have unexpected behavior if you have more than one injector (with ServletModule) running in the same JVM. Please consult the Guice documentation at http://code.google.com/p/google-guice/wiki/Servlets for more information.
Dec 13, 2016 7:48:18 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.slider.server.appmaster.web.rest.SliderJacksonJaxbJsonProvider as a provider class
Dec 13, 2016 7:48:18 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.hadoop.yarn.webapp.GenericExceptionHandler as a provider class
Dec 13, 2016 7:48:18 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.slider.server.appmaster.web.rest.AMWebServices as a root resource class
Dec 13, 2016 7:48:18 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Dec 13, 2016 7:48:18 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.hadoop.yarn.webapp.GenericExceptionHandler to GuiceManagedComponentProvider with the scope "Singleton"
Dec 13, 2016 7:48:18 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.slider.server.appmaster.web.rest.SliderJacksonJaxbJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
Dec 13, 2016 7:48:18 AM com.sun.jersey.api.wadl.config.WadlGeneratorLoader loadWadlGenerator
INFO: Loading wadlGenerator org.apache.slider.server.appmaster.web.rest.AMWadlGenerator
Dec 13, 2016 7:48:18 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.slider.server.appmaster.web.rest.AMWebServices to GuiceManagedComponentProvider with the scope "Singleton"
16/12/13 07:48:19 ERROR mortbay.log: Error for /
java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:870)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:834)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:795)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.apache.hadoop.http.HttpServer2$QuotingInputFilter.doFilter(HttpServer2.java:1243)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.apache.hadoop.http.NoCacheFilter.doFilter(NoCacheFilter.java:45)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by anusudarsan** [comment]
The UriBuilder error is usually not a serious one. Do you have any other stack trace in the Presto logs or Slider logs? Do you see any of the Presto components being launched at all?
