### ISSUE TITLE
Ths presto_server.py is wrong

### ISSUE THREAD

**Issue by xlows-1227** [prestodb/presto-yarn#74]
When I start presto-yarn ,The error log is ：

```
Traceback (most recent call last):
  File "/yarn/nm/usercache/root/appcache/application_1511159513629_0034/filecache/11/presto-yarn-package-1.6-SNAPSHOT-0.167.zip/package/scripts/presto_coordinator.py", line 24, in <module>
    PrestoServer('COORDINATOR').execute()
  File "/yarn/nm/usercache/root/appcache/application_1511159513629_0034/filecache/10/slider-agent.tar.gz/slider-agent/resource_management/libraries/script/script.py", line 116, in execute
    method(env)
  File "/yarn/nm/usercache/root/appcache/application_1511159513629_0034/filecache/11/presto-yarn-package-1.6-SNAPSHOT-0.167.zip/package/scripts/presto_server.py", line 50, in start
    os.symlink(format('{conf_dir}'), os.path.join(format('{presto_root}'), 'etc'))
OSError: [Errno 2] No such file or directory
```

I use CDH，How Can I fix this ?

**Comment by anuragrawat28** [comment]
I am also facing the same issue were you able to resolve it @luoruixing ?

**Comment by supercena** [comment]
o no
