### ISSUE TITLE
slider on yarn is running but cannot talk to presto

### ISSUE THREAD

**Issue by aeoles** [prestodb/presto-yarn#84]
### below is my slider status, there is not error log ,but   "allRequestsSatisfied" : false
{
  "version" : "1.0",
  "name" : "presto-yarn",
  "type" : "agent",
  "state" : 3,
  "createTime" : 1545900893424,
  "updateTime" : 1545900893521,
  "originConfigurationPath" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/snapshot",
  "generatedConfigurationPath" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/generated",
  "dataPath" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/database",
  "options" : {
    "internal.container.failure.shortlife" : "60000",
    "internal.container.failure.threshold" : "5",
    "internal.generated.conf.path" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/generated",
    "env.MALLOC_ARENA_MAX" : "4",
    "internal.am.tmp.dir" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/tmp/appmaster",
    "internal.snapshot.conf.path" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/snapshot",
    "site.global.config_dir" : "/mnt/disk1/log/presto-yarn/etc/",
    "zookeeper.hosts" : "emr-worker-1,emr-header-1,emr-header-2",
    "site.global.coordinator_host" : "${COORDINATOR_HOST}",
    "internal.data.dir.path" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/database",
    "internal.addons.dir.path" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/tmp/addons",
    "site.global.user_group" : "hadoop",
    "site.global.data_dir" : "/mnt/disk1/log/presto-yarn",
    "site.global.presto_query_max_memory" : "200GB",
    "site.global.presto_query_max_memory_per_node" : "20GB",
    "internal.application.home" : null,
    "internal.provider.name" : "agent",
    "yarn.vcores" : "1",
    "site.global.security_enabled" : "false",
    "zookeeper.quorum" : "emr-worker-1:2181,emr-header-1:2181,emr-header-2:2181",
    "site.global.catalog" : "{'hive':['connector.name=hive-hadoop2','hive.metastore.uri=thrift://emr-header-1:9083','hive.config.resources=/etc/ecm/hadoop-conf/core-site.xml, /etc/ecm/hadoop-conf/hdfs-site.xml'],'tpch': ['connector.name=t
pch']}",
    "java_home" : "usr/lib/jvm/java-1.8.0",
    "slider.cluster.directory.permissions" : "0770",
    "internal.tmp.dir" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/tmp",
    "slider.data.directory.permissions" : "0770",
    "application.def" : "hdfs://emr-cluster/slider/presto-yarn-package-1.6-SNAPSHOT-0.215.zip",
    "site.global.app_name" : "presto-server-0.215",
    "zookeeper.path" : "/services/slider/users/hadoop/presto-yarn",
    "site.global.app_user" : "hadoop",
    "site.global.app_pkg_plugin" : "${AGENT_WORK_ROOT}/app/definition/package/plugins/",
    "site.global.log_properties" : "['com.facebook.presto=DEBUG']",
    "site.global.jvm_args" : "['-server','-Xmx150G','-XX:+UseG1GC','-XX:G1HeapRegionSize=32M','-XX:+UseGCOverheadLimit','-XX:+ExplicitGCInvokesConcurrent','-XX:+HeapDumpOnOutOfMemoryError','-XX:+ExitOnOutOfMemoryError','-XX:+PrintClassHis
togramAfterFullGC']",
    "internal.application.image.path" : null,
    "internal.appdef.dir.path" : "hdfs://emr-cluster/user/hadoop/.slider/cluster/presto-yarn/tmp/appdef",
    "site.global.additional_config_properties" : "['task.max-worker-threads=100', 'distributed-joins-enabled=true']",
    "site.fs.defaultFS" : "hdfs://emr-cluster/slider",
    "site.global.presto_server_port" : "9091",
    "site.global.singlenode" : "false",
    "site.fs.default.name" : "hdfs://emr-cluster/slider",
    "application.name" : "presto-yarn"
  },
  "info" : {
    "yarn.vcores" : "32",
    "info.am.agent.status.url" : "https://emr-worker-1.cluster-69594:37225/",
    "yarn.memory" : "254976",
    "info.am.agent.ops.url" : "https://emr-worker-1.cluster-69594:42986/",
    "info.am.app.id" : "application_1543906752596_52372",
    "info.am.web.url" : "http://emr-worker-1.cluster-69594:39245/",
    "info.am.rpc.port" : "39444",
    "info.am.agent.ops.port" : "42986",
    "info.am.hostname" : "emr-worker-1.cluster-69594",
    "info.am.web.port" : "39245",
    "info.am.container.id" : "container_e12_1543906752596_52372_02_000001",
    "info.am.attempt.id" : "appattempt_1543906752596_52372_000002",
    "info.am.agent.status.port" : "37225",
    "status.application.build.info" : "Slider Core-0.92.0-incubating Built against commit# ${buildNumber} on Java 1.8.0_191 by aeoles",
    "status.hadoop.build.info" : "2.7.1",
    "status.hadoop.deployed.info" : "branch-2.7.1 @fc0a1a23fc1868e4d5ee7fa2b28a58a",
    "live.time" : "27 Dec 2018 08:54:53 GMT",
    "live.time.millis" : "1545900893424",
    "create.time" : "27 Dec 2018 08:54:53 GMT",
    "create.time.millis" : "1545900893424",
    "containers.at.am-restart" : "0",
    "status.time" : "27 Dec 2018 10:12:20 GMT",
    "status.time.millis" : "1545905540343"
  },
  "statistics" : {
    "COORDINATOR" : {
      "containers.failed.preempted" : 0,
      "containers.completed" : 0,
      "containers.failed" : 0,
      "containers.requested" : 1,
      "containers.desired" : 1,
      "containers.start.failed" : 0,
      "containers.failed.node" : 0,
      "containers.start.started" : 0,
      "containers.active.requests" : 1,
      "containers.failed.recently" : 0,
      "containers.live" : 0,
      "containers.anti-affine.pending" : 0
    },
    "slider-appmaster" : {
      "containers.completed" : 0,
      "containers.failed" : 0,
      "containers.unknown.completed" : 0,
      "containers.surplus" : 0,
      "containers.start.failed" : 0,
      "containers.start.started" : 0,
      "containers.live" : 1
    },
    "WORKER" : {
      "containers.failed.preempted" : 0,
      "containers.completed" : 0,
      "containers.failed" : 0,
      "containers.requested" : 10,
      "containers.desired" : 10,
      "containers.start.failed" : 0,
      "containers.failed.node" : 0,
      "containers.start.started" : 0,
      "containers.active.requests" : 10,
      "containers.failed.recently" : 0,
      "containers.live" : 0,
      "containers.anti-affine.pending" : 0
    }
  },
  "instances" : {
    "slider-appmaster" : [ "container_e12_1543906752596_52372_02_000001" ]
  },
  "roles" : {
    "COORDINATOR" : {
      "yarn.vcores" : "1",
      "yarn.role.priority" : "1",
      "yarn.memory" : "300000",
      "role.releasing.instances" : "0",
      "role.failed.node.instances" : "0",
      "role.requested.instances" : "1",
      "role.actual.instances" : "0",
      "role.failed.recently.instances" : "0",
      "role.failed.starting.instances" : "0",
      "yarn.component.instances" : "1",
      "role.failed.preempted.instances" : "0",
      "role.failed.instances" : "0",
      "yarn.component.placement.policy" : "1"
    },
    "slider-appmaster" : {
      "yarn.vcores" : "1",
      "yarn.component.instances" : "1",
      "yarn.memory" : "1024",
      "role.releasing.instances" : "0",
      "role.failed.preempted.instances" : "0",
      "role.failed.node.instances" : "0",
      "role.requested.instances" : "0",
      "role.failed.instances" : "0",
      "role.actual.instances" : "1",
      "role.failed.recently.instances" : "0",
      "role.failed.starting.instances" : "0"
    },
    "WORKER" : {
      "yarn.vcores" : "1",
      "yarn.role.priority" : "2",
      "yarn.memory" : "300000",
      "role.releasing.instances" : "0",
      "role.failed.node.instances" : "0",
      "role.requested.instances" : "10",
      "role.actual.instances" : "0",
      "role.failed.recently.instances" : "0",
      "role.failed.starting.instances" : "0",
      "yarn.component.instances" : "10",
      "role.failed.preempted.instances" : "0",
      "role.failed.instances" : "0",
      "yarn.component.placement.policy" : "1"
    }
  },
  "clientProperties" : { },
  "status" : {
    "live" : {
      "slider-appmaster" : {
        "container_e12_1543906752596_52372_02_000001" : {
          "name" : "container_e12_1543906752596_52372_02_000001",
          "role" : "slider-appmaster",
          "roleId" : 0,
          "createTime" : 1545900893454,
          "startTime" : 1545900893454,
          "completionTime" : 0,
          "released" : false,
          "host" : "emr-worker-1.cluster-69594",
          "hostUrl" : "http://emr-worker-1.cluster-69594:39245",
          "state" : 3,
          "exitCode" : 0
        }
      }
    }
  },
  "liveness" : {
    "allRequestsSatisfied" : false,
    "requestsOutstanding" : 11,
    "activeRequests" : 11,
    "lastAllocationTime" : 0,
    "availableResource" : {
      "memory" : 101632,
      "virtualCores" : 1
    }
  }
}

**Comment by aeoles** [comment]
below is appConfig.json
{
  "schema": "http://example.org/specification/v2.0.0",
  "metadata": {
  },
  "global": {
    "site.global.app_user": "hadoop",
    "site.global.user_group": "hadoop",
    "site.global.data_dir": "/mnt/disk1/log/presto-yarn",
    "site.global.config_dir": "/mnt/disk1/log/presto-yarn/etc/",
    "zookeeper.quorum" : "emr-header-1:2181,emr-header-2:2181,emr-worker-1:2181",
    "site.global.app_name": "presto-server-0.215",
    "site.global.app_pkg_plugin": "${AGENT_WORK_ROOT}/app/definition/package/plugins/",
    "site.global.singlenode": "false",
    "site.global.coordinator_host": "${COORDINATOR_HOST}",
    "site.global.presto_query_max_memory": "200GB",
    "site.global.presto_query_max_memory_per_node": "20GB",
    "site.global.presto_server_port": "9091",
    "site.global.catalog": "{'hive':['connector.name=hive-hadoop2','hive.metastore.uri=thrift://emr-header-1:9083','hive.config.resources=/etc/ecm/hadoop-conf/core-site.xml, /etc/ecm/hadoop-conf/hdfs-site.xml'],'tpch': ['connector.name=tpch']}",
    "site.global.jvm_args": "['-server','-Xmx150G','-XX:+UseG1GC','-XX:G1HeapRegionSize=32M','-XX:+UseGCOverheadLimit','-XX:+ExplicitGCInvokesConcurrent','-XX:+HeapDumpOnOutOfMemoryError','-XX:+ExitOnOutOfMemoryError','-XX:+PrintClassHistogramAfterFullGC']",
    "site.global.log_properties": "['com.facebook.presto=DEBUG']",
  "site.global.additional_config_properties":"['task.max-worker-threads=100', 'distributed-joins-enabled=true']",
    "application.def": "hdfs://emr-cluster/slider/presto-yarn-package-1.6-SNAPSHOT-0.215.zip",
    "java_home": "usr/lib/jvm/java-1.8.0"
  },
  "components": {
    "slider-appmaster": {
      "jvm.heapsize": "1024M"
    }
  }
}

**Comment by aeoles** [comment]
I find logs in  "site.global.data_dir" that 'distributed-joins-enabled=true' is not supported ,so I drop it and it works. However it appears another Error in yarn container logs:
```
ERROR 2018-12-28 13:52:33,565 NetUtil.py:60 - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
ERROR 2018-12-28 13:52:33,566 NetUtil.py:62 - SSLError: Failed to connect. Please check openssl library versions. 
```

referring to [this ](https://community.hortonworks.com/questions/120861/ambari-agent-ssl-certificate-verify-failed-certifi.html) I changed python cert to disable ,but I dont know if there are any other influences?

**Comment by aeoles** [comment]
And I had error like this:
```
2018-12-28T16:49:36.231+0800    WARN    main    Bootstrap
2018-12-28T16:49:36.854+0800    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:117)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:68)
```
I delete the configuration line including 'query.queue-config-file' in presto-yarn, because its dropped  befor presto v_0.215 #https://github.com/prestodb/presto/issues/11270  , hope it works

**Comment by aeoles** [comment]
only the master server user can ssh to other workers, and have access to login via internet and zk is on 
header-1:2181,header-2:2181,worker-1:2181
now coordinator can only setup on workers that get error like this
```
2018-12-28T17:57:14.743+0800    ERROR   Announcer-0     io.airlift.discovery.client.Announcer   Service announcement failed after 1.25ms. Next request will happen within 1000.00ms
``` 
how to specify coordinator to install on masters;

**Comment by aeoles** [comment]
* slider submit app to yarn via RM so that coordinator cannot distributed to header-1 or header-2 ,then I setup coordinator alone on header-1 
* remove coordinator part of resource.json
```
{
  "schema": "http://example.org/specification/v2.0.0",
  "metadata": {
  },
  "global": {
    "yarn.vcores": "1"
  },
  "components": {
    "slider-appmaster": {
    },
    "WORKER": {
      "yarn.role.priority": "2",
      "yarn.component.instances": "10",
      "yarn.component.placement.policy": "1",
      "yarn.memory": "30000"
    }
  }
}
```
* due to config in core-site.xml ,need to add hadoop lib: hadoop-lzo  to slider lib 
```
  <property>
    <name>io.compression.codecs</name>
    <value>com.hadoop.compression.lzo.LzoCodec,com.hadoop.compression.lzo.LzopCodec,org.apache.hadoop.io.compress.DefaultCodec,org.apache.hadoop.io.compress.GzipCodec,org.apache.hadoop.io.compress.BZip2Codec,org.apache.hadoop.io.compress.DeflateCodec,org.apache.hadoop.io.compress.SnappyCodec,org.apache.hadoop.io.compress.Lz4Codec</value>
  </property>
  <property>
```
* #### presto worker on yarn, coordinator not, a little bit weird
